version: '3.4'

services:
  inventorydb:
    image: postgres
  basketdb:
    image: redis:alpine
  pgadmin:
    image: dpage/pgadmin4
  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: src/services/Inventory/Inventory.Api/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/services/Basket/Basket.Api/Dockerfile

volumes:
    postgres_data:
    pgadmin_data:

